# Use container-based build
sudo: false

language: scala

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

scala:
  - 2.10.6
  - 2.11.8

jdk:
  - openjdk7
  - openjdk6

matrix:
  include:
  - scala: 2.12.0-RC1
    jdk: oraclejdk8

notifications:
  email:
    - sbt-dev-bot@googlegroups.com
